services:
  postgres:
    image: postgres:17-alpine
    container_name: database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432:5432"
    networks:
      - database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - database
    ports:
      - "8000:8000"
    environment:
      POSTGRES_ADDRESS: postgres
    env_file:
      - .env

networks:
  database: